-- MySQL Script generated by MySQL Workbench
-- Mon Dec 11 21:21:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `University` ;
USE `University` ;

-- -----------------------------------------------------
-- Table `University`.`Buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Buildings` (
  `BuildingID` INT NOT NULL AUTO_INCREMENT,
  `BuildingNumber` INT NOT NULL,
  PRIMARY KEY (`BuildingID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Floors` (
  `FloorID` INT NOT NULL AUTO_INCREMENT,
  `FloorNumber` INT NOT NULL,
  `BuildingID` INT NOT NULL,
  PRIMARY KEY (`FloorID`, `BuildingID`),
  INDEX `fk_Floors_Buildings_idx` (`BuildingID` ASC),
  CONSTRAINT `fk_Floors_Buildings`
    FOREIGN KEY (`BuildingID`)
    REFERENCES `University`.`Buildings` (`BuildingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Auditoriums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Auditoriums` (
  `AuditoriumID` INT NOT NULL AUTO_INCREMENT,
  `AuditoriumNumber` INT NOT NULL,
  `FloorID` INT NOT NULL,
  PRIMARY KEY (`AuditoriumID`, `FloorID`),
  INDEX `fk_Auditoriums_Floors1_idx` (`FloorID` ASC),
  CONSTRAINT `fk_Auditoriums_Floors1`
    FOREIGN KEY (`FloorID`)
    REFERENCES `University`.`Floors` (`FloorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Faculties` (
  `FacultyID` INT NOT NULL AUTO_INCREMENT,
  `FacultyName` NVARCHAR(50) NOT NULL,
  PRIMARY KEY (`FacultyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Departments` (
  `DepartmentID` INT NOT NULL AUTO_INCREMENT,
  `DepartmentName` NVARCHAR(50) NOT NULL,
  `FacultyID` INT NOT NULL,
  PRIMARY KEY (`DepartmentID`, `FacultyID`),
  INDEX `fk_Departments_Faculties1_idx` (`FacultyID` ASC),
  CONSTRAINT `fk_Departments_Faculties1`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `University`.`Faculties` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Specialties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Specialties` (
  `SpecialtyID` INT NOT NULL AUTO_INCREMENT,
  `SpecialtyName` NVARCHAR(50) NOT NULL,
  `DepartmentID` INT NOT NULL,
  PRIMARY KEY (`SpecialtyID`, `DepartmentID`),
  INDEX `fk_Specialties_Departments1_idx` (`DepartmentID` ASC),
  CONSTRAINT `fk_Specialties_Departments1`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `University`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Groups` (
  `GroupID` INT NOT NULL AUTO_INCREMENT,
  `GroupNumber` INT NOT NULL,
  `SpecialtyID` INT NOT NULL,
  PRIMARY KEY (`GroupID`, `SpecialtyID`),
  INDEX `fk_Groups_Specialties1_idx` (`SpecialtyID` ASC),
  CONSTRAINT `fk_Groups_Specialties1`
    FOREIGN KEY (`SpecialtyID`)
    REFERENCES `University`.`Specialties` (`SpecialtyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Professors` (
  `ProfessorID` INT NOT NULL AUTO_INCREMENT,
  `ProfessorFirstName` NVARCHAR(50) NOT NULL,
  `ProfessorLastName` NVARCHAR(50) NOT NULL,
  `DepartmentID` INT NOT NULL,
  PRIMARY KEY (`ProfessorID`, `DepartmentID`),
  INDEX `fk_Professors_Departments1_idx` (`DepartmentID` ASC),
  CONSTRAINT `fk_Professors_Departments1`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `University`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Courses` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `CourseName` NVARCHAR(50) NOT NULL,
  `StudentID` INT NOT NULL,
  `ProfessorID` INT NOT NULL,
  `DepartmentID` INT NOT NULL,
  PRIMARY KEY (`CourseID`, `ProfessorID`, `DepartmentID`),
  UNIQUE INDEX `StudentID_UNIQUE` (`StudentID` ASC),
  INDEX `fk_Courses_Professors1_idx` (`ProfessorID` ASC),
  INDEX `fk_Courses_Departments1_idx` (`DepartmentID` ASC),
  CONSTRAINT `fk_Courses_Professors1`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `University`.`Professors` (`ProfessorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `University`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`Students` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `StudentFirstName` NVARCHAR(50) NOT NULL,
  `StudentLastName` NVARCHAR(50) NOT NULL,
  `FacultyID` INT NOT NULL,
  `GroupID` INT NOT NULL,
  `SpecialtyID` INT NOT NULL,
  `CourseID` INT NOT NULL,
  PRIMARY KEY (`StudentID`, `FacultyID`, `GroupID`, `SpecialtyID`, `CourseID`),
  INDEX `fk_Students_Faculties1_idx` (`FacultyID` ASC),
  INDEX `fk_Students_Groups1_idx` (`GroupID` ASC),
  INDEX `fk_Students_Specialties1_idx` (`SpecialtyID` ASC),
  INDEX `fk_Students_Courses1_idx` (`CourseID` ASC),
  CONSTRAINT `fk_Students_Faculties1`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `University`.`Faculties` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Groups1`
    FOREIGN KEY (`GroupID`)
    REFERENCES `University`.`Groups` (`GroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Specialties1`
    FOREIGN KEY (`SpecialtyID`)
    REFERENCES `University`.`Specialties` (`SpecialtyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Courses1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `University`.`Courses` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`StudentSchedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`StudentSchedules` (
  `StudentScheduleID` INT NOT NULL AUTO_INCREMENT,
  `StudentScheduleTable` BLOB NULL,
  `StudentID` INT NOT NULL,
  PRIMARY KEY (`StudentScheduleID`, `StudentID`),
  INDEX `fk_StudentSchedules_Students1_idx` (`StudentID` ASC),
  CONSTRAINT `fk_StudentSchedules_Students1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `University`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`StudentMarks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`StudentMarks` (
  `StudentMarkID` INT NOT NULL AUTO_INCREMENT,
  `StudentMark` INT NOT NULL,
  `StudentID` INT NOT NULL,
  PRIMARY KEY (`StudentMarkID`, `StudentID`),
  INDEX `fk_StudentMarks_Students1_idx` (`StudentID` ASC),
  CONSTRAINT `fk_StudentMarks_Students1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `University`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`StudentStatuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`StudentStatuses` (
  `StudentStatusID` INT NOT NULL AUTO_INCREMENT,
  `StudentStatusType` NVARCHAR(50) NOT NULL,
  `StudentID` INT NOT NULL,
  PRIMARY KEY (`StudentStatusID`, `StudentID`),
  INDEX `fk_StudentStatuses_Students1_idx` (`StudentID` ASC),
  CONSTRAINT `fk_StudentStatuses_Students1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `University`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`StudentFacultyNumbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`StudentFacultyNumbers` (
  `StudentFacultyNumberID` INT NOT NULL AUTO_INCREMENT,
  `StudentFacultyNumber` INT NOT NULL,
  `StudentID` INT NOT NULL,
  PRIMARY KEY (`StudentFacultyNumberID`, `StudentID`),
  INDEX `fk_StudentFacultyNumbers_Students1_idx` (`StudentID` ASC),
  CONSTRAINT `fk_StudentFacultyNumbers_Students1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `University`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`ProfessorTitles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University`.`ProfessorTitles` (
  `ProfessorTitleID` INT NOT NULL AUTO_INCREMENT,
  `ProfessorTitle` NVARCHAR(50) NOT NULL,
  `ProfessorID` INT NOT NULL,
  PRIMARY KEY (`ProfessorTitleID`, `ProfessorID`),
  INDEX `fk_ProfessorTitles_Professors1_idx` (`ProfessorID` ASC),
  CONSTRAINT `fk_ProfessorTitles_Professors1`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `University`.`Professors` (`ProfessorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
